/// Flutter icons Ouricon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Ouricon
///      fonts:
///       - asset: fonts/Ouricon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Ouricon {
  Ouricon._();

  static const _kFontFam = 'Ouricon';
  static const _kFontPkg = null;

  static const IconData connections_inc_ = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
